const { chromium } = require('playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const { fixture } = require('./fixtures.cjs');
const root = path.resolve(__dirname, '..'), out = path.join(root, 'test-results');
let browser, page; const errors = [];
const settle = () => page.waitForFunction(() => document.querySelector('#app').getAttribute('aria-busy') !== 'true');
const click = async name => { await page.locator('[data-action="' + name + '"]').first().click(); await settle(); };
const bundle = () => page.evaluate(() => PFA_APP.getBundle());
const pending = async () => (await bundle()).requests.find(r => ['CREATED','COPIED','WAITING_RESPONSE','INVALID_RESPONSE'].includes(r.status));
async function importResponse(options) {
  const r = await pending(); await page.locator('#response-input').fill(fixture(r, options).response); await click('import-response');
  await page.waitForFunction(rid => PFA_APP.getBundle().requests.find(r => r.id === rid)?.status === 'COMPLETED', r.id);
}
(async () => {
  await fs.mkdir(out, { recursive: true });
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  page = await browser.newPage({ viewport: { width: 1366, height: 900 } }); page.on('pageerror', e => errors.push(e.message));
  await page.goto(pathToFileURL(path.join(root, 'index.html')).href); await page.waitForFunction(() => !!window.PFA_APP);
  await page.locator('#prompt-editor').fill('Investiga el mercado con fuentes.'); await click('primary'); await importResponse();
  await click('primary');
  const v2Text = '\nInvestiga el mercado con las fuentes proporcionadas.\nSi faltan datos, indícalo.\nDevuelve una tabla.\n' + 'Contexto de prueba para un prompt extenso.\n'.repeat(100);
  await importResponse({ prompt: v2Text }); await click('primary'); await importResponse(); await click('primary'); await importResponse();
  const original = await bundle(), v2 = original.versions[1];
  await click('refine-again');
  let r = await pending(); assert.equal(r.operation, 'REFINE'); assert.deepEqual(r.sourceVersionIds, [v2.id]);
  assert.match(await page.locator('#dialog-title').innerText(), /Refinamiento · V2/);
  assert.equal((await bundle()).versions.length, 2, 'Refinar no debe crear antes una edición manual fantasma');
  const partialResponse = '\n\nReporte parcial que empieza con líneas vacías.\n';
  await page.locator('#response-input').fill(partialResponse); await click('close-dialog'); await click('refine-again');
  assert.equal(await page.locator('#response-input').inputValue(), partialResponse);
  const v3Text = '\n' + v2Text + '\nDistingue el cálculo de una liquidación del pago efectivo.';
  await importResponse({ prompt: v3Text });
  let b = await bundle(); assert.equal(b.versions.length, 3); assert.equal(b.versions[2].source, 'REFINEMENT');
  assert.equal(b.versions[2].parentVersionId, v2.id); assert.equal(b.versions[2].content, v3Text); assert.equal(b.versions[1].content, v2Text);
  await click('primary'); await importResponse({ better: true }); await click('primary'); r = await pending();
  assert.deepEqual(r.sourceVersionIds, [v2.id, b.versions[2].id]); await importResponse();
  await page.locator('[data-view="prompt"]').click(); await settle();
  assert.equal(await page.locator('#prompt-editor').inputValue(), v3Text);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('denied'); } } }));
  await click('copy-prompt'); assert.equal(await page.locator('#manual-copy').inputValue(), v3Text); await click('close-dialog');
  await page.reload(); await page.waitForFunction(() => !!window.PFA_APP);
  assert.equal(await page.locator('#prompt-editor').inputValue(), v3Text); assert.equal((await bundle()).versions.length, 3);
  await page.locator('[data-view="versions"]').click(); await settle(); await click('edit-manually');
  await page.locator('#prompt-editor').fill(v3Text.slice(1)); await click('primary');
  assert.equal((await pending()).operation, 'EVALUATE'); await click('cancel-request');
  await page.locator('[data-view="versions"]').click(); await settle();
  const notice = page.locator('[data-text-change="EDGE_BLANK_LINES"]');
  assert.match(await notice.innerText(), /edición manual/);
  const stats = await page.locator('.delta-stats').innerText();
  assert.match(stats, /-0,02%/); assert.doesNotMatch(stats, /-0%/);
  await page.screenshot({ path: path.join(out, 'blank-lines-explanation.png'), fullPage: true });
  assert.deepEqual(errors, []);
  await fs.writeFile(path.join(out, 'iteration-verification.json'), JSON.stringify({ passed: true, date: new Date().toISOString(), checks: ['Segunda iteración V2 → V3 conserva saltos de línea, usa REFINE y no crea versiones fantasma', 'Respuesta parcial, copia manual y reapertura conservan líneas iniciales'], pageErrors: errors }, null, 2));
  console.log('PASS segunda iteración real por la interfaz, sin ediciones fantasma ni pérdida de líneas iniciales');
  await browser.close();
})().catch(async error => { console.error(error); if (browser) await browser.close(); process.exitCode = 1; });
