const { chromium } = require('playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const { fixture, pack } = require('./fixtures.cjs');
const root = path.resolve(__dirname, '..'), out = path.join(root, 'test-results');
let browser, page; const errors = [];
const settle = () => page.waitForFunction(() => document.querySelector('#app').getAttribute('aria-busy') !== 'true');
const click = async name => { await page.locator('[data-action="' + name + '"]').first().click(); await settle(); };
const bundle = () => page.evaluate(() => PFA_APP.getBundle());
async function importFixture(behavioralResult) {
  const b = await bundle(), req = b.requests.find(r => ['CREATED','WAITING_RESPONSE','COPIED','INVALID_RESPONSE'].includes(r.status));
  const f = fixture(req);
  if (behavioralResult) { f.data.hypotheses[0].behavioralResult = behavioralResult; f.response = pack(req, f.data); }
  await page.locator('#response-input').fill(f.response); await click('import-response');
  assert.equal((await bundle()).requests.find(r => r.id === req.id).status, 'COMPLETED');
}
(async () => {
  await fs.mkdir(out, { recursive: true });
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }); page.on('pageerror', e => errors.push(e.message));
  await page.goto(pathToFileURL(path.join(root, 'index.html')).href); await page.waitForFunction(() => !!window.PFA_APP);
  await page.locator('#prompt-editor').fill('Extrae la edad de la entrada como JSON.'); await click('primary'); await importFixture();
  await click('primary'); await importFixture(); await click('primary'); await importFixture();
  await page.locator('[data-view="tests"]').click(); await settle();
  await click('test-new');
  await page.locator('#test-name').fill('Edad ausente · reconocer el límite');
  await page.locator('#test-type').selectOption('EDGE');
  await page.locator('#test-input').fill('La persona se llama Ana. No se proporciona su edad.');
  await page.locator('#test-context').fill('Extraer solo datos explícitos.');
  await page.locator('#test-expected').fill('Una edad desconocida debe representarse como null.');
  await page.locator('[data-check-value]').fill('No inventa una edad.');
  await page.locator('[data-check-hypothesis]').selectOption({ index: 1 });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.querySelector('#dialog').scrollWidth <= document.querySelector('#dialog').clientWidth));
  await page.locator('[data-check-hypothesis]').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, 'hypothesis-editor-mobile.png') });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await click('test-add-check');
  await page.locator('[data-check-kind]').nth(1).selectOption('JSON');
  await click('test-add-check'); await page.locator('[data-check-kind]').nth(2).selectOption('CONTAINS'); await page.locator('[data-check-value]').nth(2).fill('null');
  await click('test-save-case');
  const caseId = (await bundle()).tests[0].id;
  assert.equal((await bundle()).tests[0].checks[0].hypothesis.hypothesisId, 'H1');
  assert.match(await page.locator('main').innerText(), /Hipótesis: V1 → V2/);
  await click('test-prepare'); await page.locator('#run-model').fill('Modelo de prueba — sin servicio externo'); await click('test-create-run');
  assert.ok(!(await page.locator('.test-output details .raw').first().innerText()).includes('debe representarse como null'));
  await page.locator('#test-response-A').fill('{"edad":25}'); await click('close-dialog');
  await click('test-open-run'); assert.equal(await page.locator('#test-response-A').inputValue(), '{"edad":25}');
  await page.locator('#test-response-B').fill('{"edad":null}');
  await page.locator('[data-human][data-side="A"] select').selectOption('FAIL'); await page.locator('[data-human][data-side="A"] textarea').fill('Inventó 25 sin evidencia.');
  await page.locator('[data-human][data-side="B"] select').selectOption('PASS'); await page.locator('[data-human][data-side="B"] textarea').fill('Reconoce el dato ausente con null.');
  await click('test-finish');
  assert.match(await page.locator('#dialog').innerText(), /B mejora/);
  assert.match(await page.locator('.test-hypotheses').innerText(), /1 comprobación · 1 mejora/);
  assert.equal(await page.locator('#test-response-A').getAttribute('readonly'), '');
  await page.screenshot({ path: path.join(out, 'tests-results-desktop.png') });
  let b = await bundle(); assert.equal(b.testRuns[0].status, 'COMPLETED'); assert.equal(b.testRuns[0].results.A[0].method, 'HUMAN');
  await click('test-evidence'); b = await bundle(); const request = b.requests.at(-1);
  assert.deepEqual(request.testRunIds, [b.testRuns[0].id]); assert.match(request.packageText, /USER_REPORTED/);
  await importFixture('CONFIRMED'); assert.match(await page.locator('main').innerText(), /Estructura \+ pruebas/);
  assert.match(await page.locator('main').innerText(), /Confirmada en estos casos/);
  await page.screenshot({ path: path.join(out, 'hypothesis-comparison-desktop.png'), fullPage: true });
  assert.match(await page.locator('main').innerText(), /2 respuestas adjuntas/);
  await page.locator('[data-view="tests"]').click(); await settle();
  await page.screenshot({ path: path.join(out, 'tests-page-desktop.png'), fullPage: true });
  await click('test-edit'); await page.locator('#test-input').fill('La persona se llama Luis. No se proporciona su edad.'); await click('test-save-case');
  b = await bundle(); assert.equal(b.tests[0].revision, 2); assert.equal(b.testRuns[0].testSnapshot.revision, 1);
  await click('test-open-run'); await click('test-repeat'); await click('test-create-run');
  await page.locator('#test-response-A').fill('{}'); await page.locator('#test-response-B').fill('{}'); await click('test-finish');
  assert.match(await page.locator('#dialog').innerText(), /Inconcluso/);
  await click('close-dialog');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(out, 'tests-page-mobile.png'), fullPage: true });
  await click('test-open-run'); assert.ok(await page.evaluate(() => document.querySelector('#dialog').getBoundingClientRect().width <= innerWidth));
  await page.screenshot({ path: path.join(out, 'tests-results-mobile.png') }); await click('close-dialog');
  const dl = page.waitForEvent('download'); await click('export-project'); const file = path.join(out, 'testing-roundtrip.pfa.json'); await (await dl).saveAs(file);
  await page.locator('#file-input').setInputFiles(file); await page.waitForFunction(() => PFA_APP.getBundle().project.title.endsWith('(copia)'));
  b = await bundle(); assert.equal(b.testRuns.length, 2); assert.notEqual(b.tests[0].id, caseId); assert.equal(b.testRuns[0].testId, b.tests[0].id);
  assert.equal(b.tests[0].checks[0].hypothesis.refinementId, b.refinements[0].id);
  assert.equal(b.testRuns[0].testSnapshot.checks[0].hypothesis.refinementId, b.refinements[0].id);
  await page.reload(); await page.waitForFunction(() => !!window.PFA_APP); assert.equal((await bundle()).testRuns.length, 2);
  const regex = await page.evaluate(async () => {
    const checks = [{ id: 'rx', kind: 'REGEX', value: '^(a+)+$' }];
    const r = { testSnapshot: { checks }, responseA: 'a'.repeat(30) + '!', responseB: 'aaaa', humanA: {}, humanB: {} };
    return await PFA.Testing.assess(r);
  });
  assert.equal(regex.A[0].status, 'ERROR'); assert.equal(regex.B[0].status, 'PASS');
  assert.deepEqual(errors, []);
  console.log('PASS casos, checks locales y humanos, borrador, comparación con evidencia, repetición, revisión inmutable, móvil y exportación con colisiones; regex limitada');
  await browser.close();
})().catch(async error => { console.error(error); if (browser) await browser.close(); process.exitCode = 1; });
